[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
calculator = "8dUuzfFK1qj95qBBbByqUFWAAxfxXyPDYR7hgpo7S8N9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/workspaces/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
