[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_dapp = "H7vC9XffKTzjKcZyEMjmrfynLL1LzgfB8T4L5c6VqFHF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/workspaces/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

