[features]
seeds = false
skip-lint = false
[programs.localnet]
basic_dapp = "DBh9E7BKAPhfys4X4DswGhqrUM4QXc6eRiXD3Lh9uZT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/windss/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
